repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit, manual]
      - id: trailing-whitespace
        stages: [commit, manual]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: python
        stages: [manual]
        args: ["check", "--fix", "--select", "I", "--no-cache"]
      - id: ruff-format
        name: ruff-format
        entry: ruff
        language: python
        stages: [commit, manual]
        args: ["format", "--no-cache", "--quiet"]
        types_or: [python]
      - id: mypy
        name: mypy
        entry: sh -c "mypy src/"
        language: python
        stages: [commit, manual]
        types_or: [python]
        verbose: true
